export const mockWordData = {
    words: [
        {
            word: 'artificial',
            pos: 'adjective',
            meaning: '인공의, 인위적인',
            difficulty: '중급',
            exampleSentence: 'Artificial intelligence is transforming our world.',
            translatedSentence: '인공지능은 우리의 세계를 변화시키고 있습니다.',
            videoId: 'video1',
            subtitleId: 1,
            createdAt: '2024-03-20T10:00:00Z',
        },
        {
            word: 'intelligence',
            pos: 'noun',
            meaning: '지능, 지성',
            difficulty: '중급',
            exampleSentence: 'Human intelligence is still superior to artificial intelligence in many ways.',
            translatedSentence: '인간의 지능은 많은 면에서 인공지능보다 우수합니다.',
            videoId: 'video1',
            subtitleId: 1,
            createdAt: '2024-03-20T10:00:00Z',
        },
        {
            word: 'transform',
            pos: 'verb',
            meaning: '변형시키다, 변화시키다',
            difficulty: '중급',
            exampleSentence: 'Technology has transformed how we communicate.',
            translatedSentence: '기술은 우리의 소통 방식을 변화시켰습니다.',
            videoId: 'video1',
            subtitleId: 1,
            createdAt: '2024-03-20T10:00:00Z',
        },
        {
            word: 'potential',
            pos: 'noun',
            meaning: '잠재력',
            difficulty: '중급',
            exampleSentence: 'The potential of AI is enormous.',
            translatedSentence: 'AI의 잠재력은 엄청납니다.',
            videoId: 'video1',
            subtitleId: 2,
            createdAt: '2024-03-20T10:00:00Z',
        },
        {
            word: 'revolutionize',
            pos: 'verb',
            meaning: '혁신하다',
            difficulty: '고급',
            exampleSentence: 'This new technology will revolutionize the industry.',
            translatedSentence: '이 새로운 기술은 산업을 혁신할 것입니다.',
            videoId: 'video1',
            subtitleId: 2,
            createdAt: '2024-03-20T10:00:00Z',
        },
        {
            word: 'implement',
            pos: 'verb',
            meaning: '구현하다, 시행하다',
            difficulty: '고급',
            exampleSentence: 'We need to implement these changes carefully.',
            translatedSentence: '우리는 이러한 변화들을 신중하게 시행해야 합니다.',
            videoId: 'video1',
            subtitleId: 3,
            createdAt: '2024-03-20T10:00:00Z',
        },
        {
            word: 'optimize',
            pos: 'verb',
            meaning: '최적화하다',
            difficulty: '고급',
            exampleSentence: 'The system optimizes performance automatically.',
            translatedSentence: '시스템은 성능을 자동으로 최적화합니다.',
            videoId: 'video1',
            subtitleId: 4,
            createdAt: '2024-03-20T10:00:00Z',
        },
        {
            word: 'innovation',
            pos: 'noun',
            meaning: '혁신',
            difficulty: '고급',
            exampleSentence: 'Innovation drives progress in technology.',
            translatedSentence: '혁신은 기술의 발전을 이끕니다.',
            videoId: 'video1',
            subtitleId: 5,
            createdAt: '2024-03-20T10:00:00Z',
        },
        {
            word: 'algorithm',
            pos: 'noun',
            meaning: '알고리즘',
            difficulty: '고급',
            exampleSentence: 'Machine learning algorithms can process vast amounts of data.',
            translatedSentence: '머신러닝 알고리즘은 방대한 양의 데이터를 처리할 수 있습니다.',
            videoId: 'video1',
            subtitleId: 6,
            createdAt: '2024-03-20T10:00:00Z',
        },
        {
            word: 'breakthrough',
            pos: 'noun',
            meaning: '돌파구, 획기적 진전',
            difficulty: '고급',
            exampleSentence: 'Scientists made a major breakthrough in cancer research.',
            translatedSentence: '과학자들은 암 연구에서 큰 돌파구를 마련했습니다.',
            videoId: 'video1',
            subtitleId: 7,
            createdAt: '2024-03-20T10:00:00Z',
        },
        {
            word: 'neural',
            pos: 'adjective',
            meaning: '신경의',
            difficulty: '고급',
            exampleSentence: 'Neural networks mimic the human brain.',
            translatedSentence: '신경망은 인간의 뇌를 모방합니다.',
            videoId: 'video1',
            subtitleId: 8,
            createdAt: '2024-03-20T10:00:00Z',
        },
        {
            word: 'pattern',
            pos: 'noun',
            meaning: '패턴',
            difficulty: '중급',
            exampleSentence: 'The system recognizes patterns in the data.',
            translatedSentence: '시스템은 데이터의 패턴을 인식합니다.',
            videoId: 'video1',
            subtitleId: 9,
            createdAt: '2024-03-20T10:00:00Z',
        },
        {
            word: 'scalable',
            pos: 'adjective',
            meaning: '확장 가능한',
            difficulty: '고급',
            exampleSentence: 'Cloud computing provides scalable solutions.',
            translatedSentence: '클라우드 컴퓨팅은 확장 가능한 솔루션을 제공합니다.',
            videoId: 'video1',
            subtitleId: 10,
            createdAt: '2024-03-20T10:00:00Z',
        },
        {
            word: 'cybersecurity',
            pos: 'noun',
            meaning: '사이버 보안',
            difficulty: '고급',
            exampleSentence: 'Cybersecurity is crucial in the digital age.',
            translatedSentence: '사이버 보안은 디지털 시대에 매우 중요합니다.',
            videoId: 'video1',
            subtitleId: 11,
            createdAt: '2024-03-20T10:00:00Z',
        },
        {
            word: 'blockchain',
            pos: 'noun',
            meaning: '블록체인',
            difficulty: '고급',
            exampleSentence: 'Blockchain technology ensures secure transactions.',
            translatedSentence: '블록체인 기술은 안전한 거래를 보장합니다.',
            videoId: 'video1',
            subtitleId: 12,
            createdAt: '2024-03-20T10:00:00Z',
        },
    ],
}
