export const mockQuizData = {
    words: [
        {
            word: 'artificial',
            pos: 'adjective',
            meaning: '인공의, 인위적인',
            difficulty: 'MEDIUM',
            exampleSentence: 'Artificial intelligence is transforming our world.',
            translatedSentence: '인공지능은 우리의 세계를 변화시키고 있습니다.',
        },
        {
            word: 'intelligence',
            pos: 'noun',
            meaning: '지능, 지성',
            difficulty: 'MEDIUM',
            exampleSentence: 'Human intelligence is still superior to artificial intelligence in many ways.',
            translatedSentence: '인간의 지능은 많은 면에서 인공지능보다 우수합니다.',
        },
        {
            word: 'transform',
            pos: 'verb',
            meaning: '변형시키다, 변화시키다',
            difficulty: 'MEDIUM',
            exampleSentence: 'Technology has transformed how we communicate.',
            translatedSentence: '기술은 우리의 소통 방식을 변화시켰습니다.',
        },
        {
            word: 'potential',
            pos: 'noun',
            meaning: '잠재력',
            difficulty: 'MEDIUM',
            exampleSentence: 'The potential of AI is enormous.',
            translatedSentence: 'AI의 잠재력은 엄청납니다.',
        },
        {
            word: 'revolutionize',
            pos: 'verb',
            meaning: '혁신하다',
            difficulty: 'HARD',
            exampleSentence: 'This new technology will revolutionize the industry.',
            translatedSentence: '이 새로운 기술은 산업을 혁신할 것입니다.',
        },
        {
            word: 'implement',
            pos: 'verb',
            meaning: '구현하다, 시행하다',
            difficulty: 'HARD',
            exampleSentence: 'We need to implement these changes carefully.',
            translatedSentence: '우리는 이러한 변화들을 신중하게 시행해야 합니다.',
        },
        {
            word: 'optimize',
            pos: 'verb',
            meaning: '최적화하다',
            difficulty: 'HARD',
            exampleSentence: 'The system optimizes performance automatically.',
            translatedSentence: '시스템은 성능을 자동으로 최적화합니다.',
        },
        {
            word: 'innovation',
            pos: 'noun',
            meaning: '혁신',
            difficulty: 'HARD',
            exampleSentence: 'Innovation drives progress in technology.',
            translatedSentence: '혁신은 기술의 발전을 이끕니다.',
        },
        {
            word: 'algorithm',
            pos: 'noun',
            meaning: '알고리즘',
            difficulty: 'HARD',
            exampleSentence: 'Machine learning algorithms can process vast amounts of data.',
            translatedSentence: '머신러닝 알고리즘은 방대한 양의 데이터를 처리할 수 있습니다.',
        },
        {
            word: 'breakthrough',
            pos: 'noun',
            meaning: '돌파구, 획기적 진전',
            difficulty: 'HARD',
            exampleSentence: 'Scientists made a major breakthrough in cancer research.',
            translatedSentence: '과학자들은 암 연구에서 큰 돌파구를 마련했습니다.',
        },
    ],
}
