export const mockQuizData = {
    quizId: 15,
    quizItems: [
        {
            id: 1,
            word: 'overwhelmed',
            meaning: '압도된, 부담을 느끼는',
            original: "I've been feeling overwhelmed with all this work lately.",
            question: "I've been feeling {} with all this work lately.",
            quizId: 15,
            wordbookItemId: 101,
        },
        {
            id: 2,
            word: 'procrastinate',
            meaning: '미루다, 꾸물거리다',
            original: 'I tend to procrastinate when I have difficult tasks.',
            question: 'I tend to {} when I have difficult tasks.',
            quizId: 15,
            wordbookItemId: 102,
        },
        {
            id: 3,
            word: 'take off',
            meaning: '이륙하다, 출발하다',
            original: 'The plane will take off in 10 minutes.',
            question: 'The plane will {} in 10 minutes.',
            quizId: 15,
            wordbookItemId: 103,
        },
        {
            id: 4,
            word: 'overwhelmed',
            meaning: '아, 나는 정말 압도된 기분이야. 지난 2주 동안 너무 많이 먹은 것 같아.',
            original: "Oh I've been damn overwhelmed. I feel like I've ate so much in the past two weeks.",
            question: "Oh I've been damn {}. I feel like I've ate so much in the past two weeks.",
            quizId: 15,
            wordbookItemId: 104,
        },
        {
            id: 5,
            word: 'look forward to',
            meaning: '기대하다',
            original: 'I look forward to seeing you at the party.',
            question: 'I {} seeing you at the party.',
            quizId: 15,
            wordbookItemId: 105,
        },
    ],
}
